# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      opreratingSystem: ubuntu-latest'
    mac:
      opreratingSystem: macos-latest'

pool:
  vmImage: $(operatinSystem)

steps:
- script: echo Runing on $(operatinSystem)
  displayName: 'Run a one-line script'
